name: Build package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.7
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create archive
      run: |
        export zip_path=$(pwd)
        zip --exclude test_*.py --exclude *.pyc --exclude *.txt -r ${{ZIP_PATH}}/${{ZIP_NAME}} recycle_bot yc_functions.py
        pip install -r requirements.txt --root requirements
        cd requirements/usr/local/lib/python3.7/site-packages/
        zip --exclude *.pyc -ur ${{ZIP_PATH}}/${{ZIP_NAME}} *

    - uses: actions/upload-artifact@v1
      with:
        name: ${{ZIP_NAME}}
        path: ${{ZIP_PATH}}
