name: Collect data

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: actions/download-artifact@v1
      with:
        name: ${{ZIP_NAME}}
        path: ${{ZIP_PATH}}

    - uses: actions/setup-python@v1
    - name: Set up Python 3.7
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create archive
      run: |
        export PYTHONPATH = $(pwd)
        python recycle_bot/load_data.py
        mv results.json recycle_bot

    - uses: actions/upload-artifact@v1
      with:
        name: my-artifact
        path: path/to/artifact
